#!/usr/bin/env python3
"""Regenerate theme/fonts.scss: the DESIGN.md faces, inlined as data URIs.

The deck has to render with no network at the venue, so the Google Fonts
`@import` is baked into the theme instead of fetched. Data URIs (rather than
woff2 files next to the SCSS) because the compiled CSS lands somewhere under
`slides_files/libs/revealjs/dist/theme/`, and no relative path from there to
`theme/fonts/` survives both `quarto preview` and a served render.

Variable faces, so one file covers every weight DESIGN.md 5.1 asks for.
Only the latin + latin-ext subsets are kept (~180 KB total).

    python3 theme/build_fonts.py
"""

import base64
import pathlib
import re
import urllib.request

CSS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Inter:wght@400..900"
    "&family=Source+Code+Pro:wght@400..600"
    "&display=swap"
)
# css2 serves woff2 only to browsers that advertise support.
UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/126.0 Safari/537.36"
)
SUBSETS = ("latin", "latin-ext")
OUT = pathlib.Path(__file__).with_name("fonts.scss")


def get(url):
    return urllib.request.urlopen(
        urllib.request.Request(url, headers={"User-Agent": UA})
    ).read()


def main():
    css = get(CSS_URL).decode()
    blocks = re.findall(r"/\* ([\w-]+) \*/\s*(@font-face \{.*?\})", css, re.S)

    out = [
        "// Generated by theme/build_fonts.py - do not edit.",
        "// DESIGN.md 5.1 faces, inlined so the deck needs no network.",
        "",
    ]
    for subset, block in blocks:
        if subset not in SUBSETS:
            continue
        url = re.search(r"url\((https://[^)]+)\)", block).group(1)
        b64 = base64.b64encode(get(url)).decode()
        out.append(f"/* {subset} */")
        out.append(
            re.sub(
                r"url\(https://[^)]+\)",
                f"url(data:font/woff2;base64,{b64})",
                block,
            )
        )
        out.append("")

    OUT.write_text("\n".join(out))
    print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
